# Site settings
title: Stefanos Margaritis
email: stefenmarg@gmail.com
description: 'It is a  professional portfolio, where I showcase my academic publications,  projects, insightful blog posts and a detailed curriculum vitae. This platform serves as a comprehensive overview of my contributions and achievements in Information technology. Available to explore are my research findings, innovative projects, and professional journey.'

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stefenmarg.github.io" # the base hostname & protocol for your site
ownerProfilePicture: 'https://avatars.githubusercontent.com/u/145908944'

collections:
  publications:
    output: true
    permalink: /publications/:title
  projects:
    output: true
    permalink: /publications/:title

# Build settings
markdown: kramdown
